# Generated by Django 4.2.13 on 2024-07-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
