# Generated by Django 4.2.13 on 2024-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0002_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
