# Generated by Django 4.2.13 on 2024-07-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0006_remove_post_created_remove_post_modified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Untitled', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='medium',
            field=models.CharField(default='uncategorised', max_length=255),
        ),
    ]
