# Generated by Django 5.0.7 on 2024-07-29 15:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('POST', '0012_remove_post_featured_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='header_image'),
        ),
    ]
